title: KieronPlay
description: Your gaming platform
baseurl: ""
url: "https://kieronplay.ebiya.sg"
logo: /assets/images/logo.png


# Navigation
header_pages:
  - index.html
  - about.md
  - payment.md
  - contact.md

# Build settings
theme: minima
